security:
    providers:
        in_memory:
            memory: ~
        administration_provider:
            entity: { class: AdministrationBundle\Entity\Administrator, property: username }
        app_provider:
            entity: { class: AdministrationBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|img|js|lib)/
            security: false
        api:
            pattern:    ^/api/
            http_basic: ~
            provider: app_provider
        administration:
            pattern:    ^/administration/
            form_login:
                provider: administration_provider
                csrf_provider: security.csrf.token_manager
                default_target_path: /administration/
                always_use_default_target_path: true
                check_path: /administration/login_check
                login_path: /administration/login
            logout:
                path:   /administration/logout
                target: /
            anonymous:    true
        app:
            pattern:    ^/app
            form_login:
                provider: app_provider
                csrf_provider: security.csrf.token_manager
                default_target_path: /app/
                always_use_default_target_path: true
                check_path: /app/login_check
                login_path: /app/login
            logout:
                path:   /app/logout
                target: /
            anonymous:    true
        default:
            anonymous: ~

    encoders:
        AdministrationBundle\Entity\Administrator:
            algorithm: bcrypt
            cost:      12
        AdministrationBundle\Entity\User:
            algorithm: bcrypt
            cost:      12
        FOSUserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/api/, roles: ROLE_USER, requires_channel: https }
        - { path: ^/administration/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/administration/, roles: ROLE_ADMIN, requires_channel: https }
        - { path: ^/app/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/app/, roles: ROLE_USER, requires_channel: https }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
