<?php

/**
 * This file is part of The OBMS project: https://github.com/obms/obms
 *
 * Copyright (c) Jaime Niñoles-Manzanera Jimeno.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace AppBundle\Entity;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository {
	/**
	 * Devuelve todas las notificaciones ordenadas por fecha.
	 *
	 * @see \Doctrine\ORM\EntityRepository::findAll()
	 */
	public function findAll() {
		$manager = $this->getEntityManager ();

		$dql = "SELECT n FROM AdministrationBundle:Notificacion n ORDER BY n.fecha asc";
		$result = $manager->createQuery ( $dql )->getResult ();

		return $result;
	}
}
