<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SalesNoteDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesNoteDetailRepository extends EntityRepository
{
}
