<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StorageStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageStockRepository extends EntityRepository
{
}
