<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StorageInventoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageInventoryRepository extends EntityRepository
{
}
